included:
  - Catalyst
  - CatalystDemo

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - empty_count
  - contains_over_filter_is_empty
  - force_unwrapping
  - toggle_bool
  - let_var_whitespace
  - operator_usage_whitespace
  - vertical_parameter_alignment_on_call

excluded:
  - .build
  - DerivedData
  - CatalystDemo/Demo/CatalystDemoUITests/*
  - CatalystDemo/Demo/CatalystDemoTests/*

disabled_rules:
  - identifier_name
  - line_length
  - file_length
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - force_cast
  - force_try
  - todo
  - nesting
  - valid_ibinspectable
  - computed_accessors_order
  - inclusive_language
  - trailing_whitespace
  - orphaned_doc_comment
  - type_name
  - private_over_fileprivate
  - number_separator
  - unused_closure_parameter
  - large_tuple
  - multiline_function_chains
  - non_optional_string_data_conversion