name: 'Angular'
on:
  push:
    paths:
      - 'angular/**'
    tags-ignore:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build -w tokens
          npm run build:ci -w core
          npm run build catalyst -w angular
