name: 'Release'
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release level'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build -w tokens
          npm run build:ci -w core
          npm run build -w angular
      - name: Create release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm run release:${{ github.event.inputs.release }}
      - name: Commit files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push --follow-tags
      - name: Publish @haiilo/catalyst-tokens to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./tokens/package.json
      - name: Publish @haiilo/catalyst to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./core/package.json
      - name: Publish @haiilo/catalyst-angular to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./angular/dist/catalyst/package.json
      - name: Publish @haiilo/catalyst-react to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./react/package.json
      - name: 'Get release tag'
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        id: previoustag
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          body_path: CHANGELOG.md
