name: 'Tokens'
on:
  push:
    paths:
      - 'tokens/**'
defaults:
  run:
    working-directory: tokens
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: tokens/package-lock.json
      - name: Install and Build
        run: |
          npm ci -ws false
          npm run build
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: update tokens'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
