import Foundation

// This file makes the package's internal asset bundle publicly accessible.
// Icons under Resources were un-reachable because of the bundle autogenerated by SPM was having internal access level.

public extension Bundle {
    /// A helper to access the design system's resource bundle.
    static var catalyst: Bundle {
        return Bundle.module
    }
}
